# Kaggle : Santander Product Recommendation
- In this competition, you are provided with 1.5 years of customers behavior data from Santander bank to predict what new products customers will purchase.
- The data starts at 2015-01-28 and has monthly records of products a customer has, such as "credit card", "savings account", etc.
- **you will predict what additional products a customer will get in the last month, 2016-06-28, in addition to what they already have at 2016-05-28. These products are the columns named: ind_(xyz)_ult1, which are the columns #25 - #48 in the training data.**
- you will predict what a customer will buy in addition to what they already had at 2016-05-28. 

## Data Dictionary
### Variable
 - #### Property of Customer
    - fecha_dato : The table is partitioned for this column
    - ncodpers : Customer code
    - ind_empleado : Employee index(A active, B ex employed, F filial, N not employee, P pasive
    - pais_residencia : Customer's Country residence
    - sexo : Customer's sex
    - age : Age
    - fecha_alta : The data in which the customer became as the first holder of a contract in the bank
    - antiguedad : Customer seniority(in months)
    - indrel : 1(First/Primary), 99(Primary customer during the month but not at the end of the month)
    - ult_fec_cli_1t : Last date as primary customer (if he isn't at the end of the month)
    - indrel_1mes : Customer type at the begining of the month, 1(First/Primary customer), 2(co-owner), P(Potential), 3(former primary), 4(former co-owner)
    - indresi : Residence index( S(Yes) or N(No) if the residence country is the same than the bank country)
    - indext : Foreigner index(S(Yes) or N(No) if the customer's bitrh country is differenct than the bank country)
    - conyuemp : Spouse index. 1 if the customer is spouse of an employee
    - canal_entrada : channel used by the customer to join
    - indfall : Deceased index. N/S
    - tipodom : Addres type. 1, primary address
    - cod_prov : Province code (customer's address)
    - nomprov : Province name
    - ind_actividad_cliente : Activity index (1, active customer; 0, inactive customer)
    - renta : Gross income of the household
    - segmento : Segmentation : 01 - VIP, 02 - Individuals, 03 - college graduated
 - #### Products(ind_aaa_aaa_ult1)
    - ahor_ahor : Saving Account
    - aval_fin : Guarantees
    - cco_fin : Current Accounts
    - cder_fin : Derivada Account
    - cno_fin : Payroll Account
    - ctju_fin : Junior Account
    - ctma_fin : Mas particular Account
    - ctop_fin : particular Account
    - ctpp_fin : particular Plus Account
    - deco_fin : Short-term deposits
    - deme_fin : Medium-term deposits
    - dela_fin : Long-term deposits
    - ecue_fin : e-account
    - fond_inf : Funds
    - hip_fin : Mortgage
    - plan_fin : Pensions
    - pres_fin : Loans
    - reca_fin : Taxes
    - tjcr_fin : Credit Card
    - valo_fin : Securities
    - viv_fin : Home Account
    - nomina : Payroll
    - nom_pens : Pensions
    - recibo : Direct Debit

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

## 1. Data Exploratory

In [2]:
train = pd.read_csv('train_ver2.csv')

C:\Users\PhotoLab_Deep\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (5,8,11,15) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [3]:
train.tail()

fecha_dato  ncodpers ind_empleado pais_residencia sexo age  \
13647304  2016-05-28   1166765            N              ES    V  22   
13647305  2016-05-28   1166764            N              ES    V  23   
13647306  2016-05-28   1166763            N              ES    H  47   
13647307  2016-05-28   1166789            N              ES    H  22   
13647308  2016-05-28   1550586            N              ES    H  37   

          fecha_alta  ind_nuevo antiguedad  indrel       ...         \
13647304  2013-08-14        0.0         33     1.0       ...          
13647305  2013-08-14        0.0         33     1.0       ...          
13647306  2013-08-14        0.0         33     1.0       ...          
13647307  2013-08-14        0.0         33     1.0       ...          
13647308  2016-05-13        1.0          0     1.0       ...          

         ind_hip_fin_ult1 ind_plan_fin_ult1 ind_pres_fin_ult1  \
13647304                0                 0                 0   
13647305                0                 0                 0   
13647306                0                 0                 0   
13647307                0                 0                 0   
13647308                0                 0                 0   

         ind_reca_fin_ult1 ind_tjcr_fin_ult1 ind_valo_fin_ult1  \
13647304                 0                 0                 0   
13647305                 0                 0                 0   
13647306                 0                 0                 0   
13647307                 0                 0                 0   
13647308                 0                 0                 0   

         ind_viv_fin_ult1 ind_nomina_ult1  ind_nom_pens_ult1  ind_recibo_ult1  
13647304                0             0.0                0.0                0  
13647305                0             0.0                0.0                0  
13647306                0             0.0                0.0                0  
13647307                0             0.0                0.0                0  
13647308                0             0.0                0.0                0  

[5 rows x 48 columns]

In [4]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13647309 entries, 0 to 13647308
Data columns (total 48 columns):
fecha_dato               object
ncodpers                 int64
ind_empleado             object
pais_residencia          object
sexo                     object
age                      object
fecha_alta               object
ind_nuevo                float64
antiguedad               object
indrel                   float64
ult_fec_cli_1t           object
indrel_1mes              object
tiprel_1mes              object
indresi                  object
indext                   object
conyuemp                 object
canal_entrada            object
indfall                  object
tipodom                  float64
cod_prov                 float64
nomprov                  object
ind_actividad_cliente    float64
renta                    float64
segmento                 object
ind_ahor_fin_ult1        int64
ind_aval_fin_ult1        int64
ind_cco_fin_ult1         int64
ind_cder_fin_ult1  

In [5]:
train.isnull().sum()

fecha_dato                      0
ncodpers                        0
ind_empleado                27734
pais_residencia             27734
sexo                        27804
age                             0
fecha_alta                  27734
ind_nuevo                   27734
antiguedad                      0
indrel                      27734
ult_fec_cli_1t           13622516
indrel_1mes                149781
tiprel_1mes                149781
indresi                     27734
indext                      27734
conyuemp                 13645501
canal_entrada              186126
indfall                     27734
tipodom                     27735
cod_prov                    93591
nomprov                     93591
ind_actividad_cliente       27734
renta                     2794375
segmento                   189368
ind_ahor_fin_ult1               0
ind_aval_fin_ult1               0
ind_cco_fin_ult1                0
ind_cder_fin_ult1               0
ind_cno_fin_ult1                0
ind_ctju_fin_u

In [6]:
train_mixed_columns = [train.columns[i] for i in [5, 8, 11, 15]]
print('mixed types columns : ', train_mixed_columns)

mixed types columns :  ['age', 'antiguedad', 'indrel_1mes', 'conyuemp']


In [30]:
# numeric columns
number_cols = [col for col in train.columns[:24] if train[col].dtype in ['int64', 'float64']]

# categorical columns
cat_cols = [col for col in train.columns[:24] if train[col].dtype in ['object']]

print(number_cols)
print()
print(cat_cols)

['ncodpers', 'ind_nuevo', 'indrel', 'tipodom', 'cod_prov', 'ind_actividad_cliente', 'renta']

['fecha_dato', 'ind_empleado', 'pais_residencia', 'sexo', 'fecha_alta', 'ult_fec_cli_1t', 'tiprel_1mes', 'indresi', 'indext', 'conyuemp', 'canal_entrada', 'indfall', 'nomprov', 'segmento']


## Handle Mixed types columns
- 5 columns of train data
### train mixed types columns

In [7]:
print(train_mixed_columns)

['age', 'antiguedad', 'indrel_1mes', 'conyuemp']


In [9]:
# 1. age
train['age'].replace(' NA', -99, inplace = True)
train['age'] = train['age'].astype(np.int8)
train['age'].unique()

array([ 35,  23,  22,  24,  65,  28,  25,  26,  53,  27,  32,  37,  31,
        39,  63,  33,  55,  42,  58,  38,  50,  30,  45,  44,  36,  29,
        60,  57,  67,  47, -99,  34,  48,  46,  54,  84,  15,  12,   8,
         6,  83,  40,  77,  69,  52,  59,  43,  10,   9,  49,  41,  51,
        78,  16,  11,  73,  62,  66,  17,  68,  82,  95,  96,  56,  61,
        79,  72,  14,  19,  13,  86,  64,  20,  89,  71,   7,  70,  74,
        21,  18,  75,   4,  80,  81,   5,  76,  92,  93,  85,  91,  87,
        90,  94,  99,  98,  88,  97, 100, 101, 106, 103,   3,   2, 102,
       104, 111, 107, 109, 105, 112, 115, 110, 116, 108, 113, 126, 117,
       -93, 127, 114, -92], dtype=int64)

In [10]:
# 2. antihuedad
train['antiguedad'].unique()[3]

'     NA'

In [12]:
train['antiguedad'].replace('     NA', -99, inplace = True)
train['antiguedad'] = train['antiguedad'].astype(np.int8)
train['antiguedad'].unique()

array([   6,   35,   34,  -99,   33,   31,   21,   16,   27,    9,   22,
         13,   29,    8,   11,   10,   28,   24,    7,   25,   14,   26,
         12,   23,    1,   18,    4,    3,   17,   32,   30,   20,   15,
         19,   36,    5,   40,   38,   37,   39,    0,    2,   47,   44,
         42,   46,   45,   43,   41,   57,   48,   52,   49,   50,   56,
         58,   51,   55,   54,   53,   59,   62,   61,   60,   63, -117,
        -91,  118,  -92, -114,   94,  -97, -113,  105, -105,  -94, -119,
       -106, -128,  122, -100,  119,  -96,   79,   95, -124,  -95,   98,
        127,   72, -101,  108,  -93,  102, -108,  115, -110,  107,   81,
        -40, -121,   92,  121,  -58, -122,   93, -116,  110,  120, -109,
        116,   64,   77,   85,   99,   78,  100,  113, -102,  -90, -123,
        124, -115,   66,  117,   86,  -63,   80, -112,   87,  126,  -98,
        101,  -21,   88, -111,  103, -107,  109, -125,   97,   68,   84,
        -24,  125,  -79,  112,   96,   69,  -85,  -

In [13]:
# 3. indrel_1mes
train['indrel_1mes'].unique()

array([1.0, nan, 3.0, 2.0, '1.0', '1', '3', '3.0', '2.0', '4.0', 'P', '4',
       4.0, '2'], dtype=object)

In [17]:
train['indrel_1mes'].replace('P', 5, inplace = True)
train['indrel_1mes'].fillna(-99, inplace = True)
train['indrel_1mes'] = train['indrel_1mes'].astype(float).astype(np.int8)
train['indrel_1mes'].unique()

array([  1, -99,   3,   2,   4,   5], dtype=int64)

In [23]:
# 4. conyuemp
print(train['conyuemp'].unique())
train['conyuemp'].value_counts()

# It should be removed?

[nan 'N' 'S']


N    1791
S      17
Name: conyuemp, dtype: int64

In [39]:
number_cols

['ncodpers',
 'ind_nuevo',
 'indrel',
 'tipodom',
 'cod_prov',
 'ind_actividad_cliente',
 'renta']

In [45]:
for col in number_cols:
    print(train[col].unique())

[1375586 1050611 1050612 ... 1173729 1164094 1550586]
[0.         0.05956184 1.        ]
[ 1.          1.17839867 99.        ]
[1.]
[29.         13.         50.         45.         24.         20.
 10.         17.         49.          8.         37.          9.
 22.         31.          5.         40.         27.         25.
 28.          3.         42.         41.         39.          7.
 47.         36.         46.         44.         15.         32.
 23.         16.         48.         12.         26.          2.
  6.         30.         11.         26.57146961  4.         19.
 34.         35.         14.         21.         18.         33.
 38.         52.         43.          1.         51.        ]
[1.         0.         0.45781054]
[ 87218.1   35548.74 122179.11 ...  63867.66  34341.18  89018.37]


In [44]:
train[number_cols] = train[number_cols].fillna(train[number_cols].mean())

## Visualization

In [ ]:
plt.figure(figsize = (15,15))
sns.set()
sns.pairplot(train[number_cols[4:]], dropna = True)

<Figure size 1080x1080 with 0 Axes>

# Question
## 1. train.loc
- train.loc[train['age'].dtype == 'object', 'age'] - Why this code is not working?